name: make-crate
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - uses: rust-lang/crates-io-auth-action@v1
        id: auth

      - name: Publish crate
        run: cargo publish
        working-directory: monolithium
        env:
          CARGO_REGISTRY_TOKEN: ${{steps.auth.outputs.token}}
